### ISSUE TITLE
Race condition when running tests in parallel

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-common#27]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/27)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
The debbuilder job runs the tests in parallel after building and often fails during the `UNIT_Console_TEST`:

* https://build.osrfoundation.org/view/debbuild/job/ign-common-debbuilder/53/
* https://build.osrfoundation.org/view/debbuild/job/ign-common-debbuilder/52/
* https://build.osrfoundation.org/view/debbuild/job/ign-common-debbuilder/55/

There is probably a race condition somewhere in our testing code. I think a short-term fix is to disable parallel testing in our jenkins metadata.

cc: @\_jrivero_

**Comment by azeey** [comment]
I think this has been fixed by #378. It would be interesting to run tests in parallel again.
