### ISSUE TITLE
ignLogInit fails if run after console output

### ISSUE THREAD

**Issue by nkoenig** [gazebosim/gz-common#331]
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build? Source

## Description

If you run `ignLogInit` after an `ignerr`, `ignmsg`, `igndbg`, or `ignwarn` has already been executed then the log file will not receive output.

* Expected behavior: Running `ignLogInit` after a console out should start logging to file.
* Actual behavior: Only the first character is logged.

## Steps to reproduce

1. Checkout the [console_loginit_issue](https://github.com/ignitionrobotics/ign-common/tree/console_loginit_issue) branch.
2. Run the `INTEGRATION_uri` test.

**Comment by mjcarroll** [comment]
Closed by #332
