### ISSUE TITLE
SignalHandler.MultipleThreads fails for 32-bit (`i386`) architectures

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-common#35]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/35)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
The `SignalHandler.MultipleThreads` is failing during the debbuild for 32-bit (`i386`) architectures:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common2-debbuilder&build=2)](https://build.osrfoundation.org/job/ign-common2-debbuilder/2/) https://build.osrfoundation.org/job/ign-common2-debbuilder/2/

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common2-debbuilder&build=4)](https://build.osrfoundation.org/job/ign-common2-debbuilder/4/) https://build.osrfoundation.org/job/ign-common2-debbuilder/4/

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common2-debbuilder&build=6)](https://build.osrfoundation.org/job/ign-common2-debbuilder/6/) https://build.osrfoundation.org/job/ign-common2-debbuilder/6/

~~~
[ RUN      ] SignalHandler.MultipleThreads
unknown file: Failure
C++ exception with description "Resource temporarily unavailable" thrown in the test body.
[  FAILED  ] SignalHandler.MultipleThreads (36 ms)
~~~

I've also confirmed the failure on a 32-bit xenial jenkins job:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_common-ci-pr_any-xenial-i386&build=1)](https://build.osrfoundation.org/job/ignition_common-ci-pr_any-xenial-i386/1/) https://build.osrfoundation.org/job/ignition_common-ci-pr_any-xenial-i386/1/testReport/junit/(root)/SignalHandler/MultipleThreads/

**Comment by azeey** [comment]
Closing since we don't support 32 bit architectures anymore.
