### ISSUE TITLE
FreeImage 3.18 jpeg behavior change

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-common#39]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/39)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
It looks like the behavior of FreeImage for jpeg images has changed with its recent 3.18 release on homebrew. I noticed this due to a regression in gazebo's `Image_TEST`, which uses `wood.jpg`, though the `Image_TEST` in ign-common doesn't show this regression because it uses `cordless_drill.png`. I'm reporting it here because this is the target of future development. We could reproduce the failure by adding a jpeg test to `Image_TEST` in this repo.

Regression in gazebo homebrew test on August 9

* https://build.osrfoundation.org/job/gazebo-ci-gazebo7-homebrew-amd64/253/testReport/(root)/ImageTest/Image/

freeimage formula updated on August 1

* https://github.com/Homebrew/homebrew-core/commit/9f999affd653e2420671c1bc7463a21069f21144

**Comment by azeey** [comment]
@scpeters since this is referring to a test in Gazebo-classic,  not sure if it's still a valid issue. Can it be closed?
