### ISSUE TITLE
Dem code is disabled due to missing HAVE_GDAL macro

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-common#40]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/40)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
The Dem code is `ifdef`d on `HAVE_GDAL`, but that macro isn't defined anywhere, so the Dem code is never compiled.

* https://github.com/ignitionrobotics/ign-common/blob/04a9eb86b9b756fa8f8a25a40a2a3536f13a4dc5/graphics/src/Dem.cc#L33

**Comment by azeey** [comment]
Fixed in #292.
