### ISSUE TITLE
Fails to detect SSE support properly

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-common#42]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/42)) by yurivict (Bitbucket: [yurivict](https://bitbucket.org/%7B7012cf74-23b1-4689-8f6d-63be51ab0d44%7D/)).**

----------------------------------------
On my machine it prints
```
-- Searching for host SSE information
-- Could not find hardware support for SSE3 on this machine.
-- Could not find hardware support for SSSE3 on this machine.
-- Could not find hardware support for SSE4.1 on this machine.
-- Could not find hardware support for SSE4.2 on this machine.
-- SSE2 found
-- SSE4 disabled.
```
while https://gist.github.com/hi2p-perim/7855506#file-ssecheck-cpp prints
```
$ ssecheck
SSE:1
SSE2:1
SSE3:1
SSE4.1:1
SSE4.2:1
SSE4a:0
SSE5:0
AVX:0
```

**Comment by azeey** [comment]
I'm not able to reproduce this. SSE detection is handled by https://github.com/gazebosim/gz-cmake/blob/200de1b26edbad9ad1d7efd7c29dd4f2080edefa/cmake/GzCheckSSE.cmake, but it only works on Linux, macOS and Windows.
