### ISSUE TITLE
DataFrame picks up spurious all zeros row

### ISSUE THREAD

**Issue by hidmic** [gazebosim/gz-common#434]
## Environment
* OS Version: Ubuntu 20.04
* Source build, on [`main`](https://github.com/gazebosim/gz-common/tree/main) (@ https://github.com/gazebosim/gz-common/commit/d847f39ab8fb272d47b4208e15a6e0531579b4da)
  
  

## Description
* Expected behavior: reading `gz::common::DataFrame` instances from CSV streams picks up all file data.   
* Actual behavior: reading `gz::common::DataFrame` instances from CSV streams picks up an extra row at the beginning, filled with zeros.

**Comment by azeey** [comment]
Fixed by #435.
