### ISSUE TITLE
gz-common io - include nested too deeply

### ISSUE THREAD

**Issue by hidmic** [gazebosim/gz-common#470]
## Environment
* OS Version: Mac OS, Windows
* Built from [`gz-common5`](56b82ad501b64a0c51b06a79fd68aeec2766f86e) source  

## Description
* Expected behavior: downstream builds against `gz-common5` succeed
* Actual behavior: downstream builds against `gz-common5` fail with: 

  ```sh
  /usr/local/include/gz/common5/gz/common/Io.hh:24:10: error: #include nested too deeply
  ```

  E.g. https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/9405, https://build.osrfoundation.org/job/ign_gazebo-pr-win/5169.

## Steps to reproduce

1. Check https://github.com/gazebosim/gz-sim/pull/1616 (first `gz-common::io` component use).

**Comment by mjcarroll** [comment]
Fixed by #471
