### ISSUE TITLE
EnumIterator inherits from std::iterator base class which is deprecated in c++17

### ISSUE THREAD

**Issue by scpeters** [gazebosim/gz-common#505]
## Environment
* OS Version: macOS 12.6.5 (Monterey) with macOS 13.1 SDK
* Source or binary build? source build of gz-common5 as of 6f5ee941536e5c781bd826f6ce35360347d581ba (other versions too)

excerpt of `brew config`:

~~~
Clang: 14.0.0 build 1400
macOS: 12.6.5-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
~~~

## Description
* Expected behavior: package should compile without warnings
* Actual behavior: deprecation warning from `EnumIface.hh` when compiling `EnumIface_TEST.cc` since [`EnumIterator` inherits from `std::iterator`](https://github.com/gazebosim/gz-common/blob/gz-common5_5.3.1/include/gz/common/EnumIface.hh#L143-L145) and the `std::iterator` base class is [deprecated as of c++17](https://en.cppreference.com/w/cpp/iterator)

<img width="733" alt="Screen Shot 2023-04-17 at 4 27 15 PM" src="https://user-images.githubusercontent.com/3650755/232631982-c7c5dc3c-b37a-4453-9f42-d1d0b69ec9dd.png">

~~~
src/EnumIface_TEST.cc:20:
/include/gz/common/EnumIface.hh:145:12: warning: 'iterator<std::bidirectional_iterator_tag, MyType>' is deprecated [-Wdeprecated-declarations]
    : std::iterator<std::bidirectional_iterator_tag, Enum>
           ^
src/EnumIface_TEST.cc:61:32: note: in instantiation of template class 'gz::common::EnumIterator<MyType>' requested here
  common::EnumIterator<MyType> end = MY_TYPE_END;
                               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__iterator/iterator.h:27:29: note: 'iterator<std::bidirectional_iterator_tag, MyType>' has been explicitly marked deprecated here
struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 iterator
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__config:1066:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__config:1043:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
~~~

## Steps to reproduce

1. Build from source on macOS Monterey

or

1. Run https://build.osrfoundation.org/view/ign-garden/job/ignition_common-ci-gz-common5-homebrew-amd64 on one of the macOS-monterey nodes

## Output

[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_common-ci-gz-common5-homebrew-amd64&build=37)](https://build.osrfoundation.org/view/ign-garden/job/ignition_common-ci-gz-common5-homebrew-amd64/37/) https://build.osrfoundation.org/view/ign-garden/job/ignition_common-ci-gz-common5-homebrew-amd64/37/clang/

**Comment by scpeters** [comment]
@mjcarroll is there a way to fix this on released versions without breaking API? If not, I think we should suppress the warning and fix it on `main`

**Comment by azeey** [comment]
I've added the `harmonic` label to make sure we include this in Harmonic.

**Comment by mjcarroll** [comment]
> I think we should suppress the warning and fix it on main

We concluded this is the right answer after talking about it at the meeting yesterday.

**Comment by scpeters** [comment]
@mjcarroll did you have any ideas for how to fix this on `main`?

**Comment by scpeters** [comment]
fixed in https://github.com/gazebosim/gz-common/pull/529
