### ISSUE TITLE
Filesystem_TEST has some portions disabled on Windows

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-common#51]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/51)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
See [pull request #187](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/pull-requests/187), specifically [these lines](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/pull-requests/187/filesystem-functions-to-create-unique/diff#Lsrc/Filesystem_TEST.ccT547).

There is a TODO item to re-enable tests that were always failing on Windows.

**Comment by chapulina** [comment]
These are the lines referred above:

https://github.com/ignitionrobotics/ign-common/blob/9c35741099081e0ea15f926bf19adc5c11bfbb97/src/Filesystem_TEST.cc#L649-L660

This is related to removing files returning false on Windows. It's the same problem on other places like this:

https://github.com/ignitionrobotics/ign-common/blob/9c35741099081e0ea15f926bf19adc5c11bfbb97/src/Filesystem_TEST.cc#L604-L606

**Comment by peci1** [comment]
Solution posted in #128.

**Comment by peci1** [comment]
I think this issue can be closed with #128 being merged.
