### ISSUE TITLE
Use fmt or spdlog for console logging

### ISSUE THREAD

**Issue by mjcarroll** [gazebosim/gz-common#73]
We could potentially clean up a good bit of stream based logging by using something like `spdlog` or `{fmt}`

https://github.com/gabime/spdlog
https://fmt.dev/latest/index.html

Note that fmt is very similar to `std::format` which landed in C++20.

Considerations:
* Not breaking ABI
* Not breaking existing code?

**Comment by azeey** [comment]
Since we're targeting ionic, it'll be okay to break ABI.

**Comment by azeey** [comment]
Resolved by #615
